import { createSlug } from "@/lib/utils";
import type { SourceChannel, SourceRegistryEntry } from "@/lib/jobs/types";

function hostnameFromUrl(url: string) {
  return new URL(url).hostname;
}

function toHostList(urls: string[]) {
  return [...new Set(urls.map((url) => hostnameFromUrl(url)))];
}

function source(
  entry: Omit<SourceRegistryEntry, "companySlug" | "sourceChannel"> & {
    sourceChannel?: SourceChannel;
  },
): SourceRegistryEntry {
  return {
    ...entry,
    sourceChannel: entry.sourceChannel || "career",
    companySlug: createSlug(entry.company),
  };
}

function landingSource(entry: {
  id: string;
  company: string;
  companyType: string;
  sourceName: string;
  sourceChannel?: SourceChannel;
  homeUrl: string;
  careersUrl: string;
  listingUrl?: string;
  crawlMode?: SourceRegistryEntry["crawlMode"];
  allowedApplyHosts?: string[];
  sectors: string[];
  enabled?: boolean;
  notes?: string;
}) {
  const listingUrl = entry.listingUrl || entry.careersUrl;
  return source({
    id: entry.id,
    company: entry.company,
    companyType: entry.companyType,
    sourceName: entry.sourceName,
    sourceChannel: entry.sourceChannel || "career",
    homeUrl: entry.homeUrl,
    careersUrl: entry.careersUrl,
    listingUrl,
    adapter: "landingOnly",
    crawlMode: entry.crawlMode || "landing",
    allowHosts: toHostList([entry.homeUrl, entry.careersUrl, listingUrl]),
    allowedApplyHosts:
      entry.allowedApplyHosts ||
      toHostList([entry.homeUrl, entry.careersUrl, listingUrl]),
    enabled: entry.enabled ?? false,
    official: true,
    trusted: true,
    sectors: entry.sectors,
    lastVerifiedAt: "2026-05-01",
    notes: entry.notes,
  });
}

export const trustedSourceRegistry: SourceRegistryEntry[] = [
  source({
    id: "pathao-careers",
    company: "Pathao",
    companyType: "Private",
    sourceName: "Pathao Career",
    homeUrl: "https://pathao.com/",
    careersUrl: "https://careers.pathao.com/",
    listingUrl: "https://careers.pathao.com/",
    adapter: "pathaoWordPress",
    crawlMode: "html",
    allowHosts: ["careers.pathao.com", "pathao.com"],
    allowedApplyHosts: ["careers.pathao.com", "docs.google.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Technology", "Logistics"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Verified working official job board with direct job detail pages and source-linked apply URLs.",
  }),
  source({
    id: "brac-careers",
    company: "BRAC",
    companyType: "NGO",
    sourceName: "BRAC Careers",
    homeUrl: "https://www.brac.net/",
    careersUrl: "https://careers.brac.net/jobs",
    listingUrl: "https://careers.brac.net/jobs",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["careers.brac.net", "brac.net"],
    allowedApplyHosts: ["careers.brac.net", "brac.net"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["NGO", "Development"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Correct official BRAC jobs portal confirmed. This replaces the earlier generic BRAC page link.",
  }),
  landingSource({
    id: "bkash-careers",
    company: "bKash",
    companyType: "Private",
    sourceName: "bKash Career",
    homeUrl: "https://www.bkash.com/en",
    careersUrl: "https://www.bkash.com/en/career",
    crawlMode: "browser",
    sectors: ["Fintech"],
    enabled: false,
    notes:
      "Official page verified, but Cloudflare/browser challenge means this stays registered with publishing disabled until a browser-safe parser is added.",
  }),
  landingSource({
    id: "grameenphone-careers",
    company: "Grameenphone",
    companyType: "Private",
    sourceName: "Grameenphone Career",
    homeUrl: "https://www.grameenphone.com/",
    careersUrl: "https://career.grameenphone.com/",
    sectors: ["Telecom"],
    notes:
      "Updated to the direct Grameenphone career portal URL shared by the user.",
  }),
  landingSource({
    id: "banglalink-careers",
    company: "Banglalink",
    companyType: "Private",
    sourceName: "Banglalink Career",
    homeUrl: "https://www.banglalink.net/",
    careersUrl: "https://www.banglalink.net/en/careers",
    sectors: ["Telecom"],
    notes: "Updated to the Banglalink careers URL shared by the user.",
  }),
  landingSource({
    id: "nagad-careers",
    company: "Nagad",
    companyType: "Private",
    sourceName: "Nagad Career",
    homeUrl: "https://www.nagad.com.bd/",
    careersUrl: "https://www.nagad.com.bd/career/",
    sectors: ["Fintech"],
    notes: "Official Nagad career page verified.",
  }),
  landingSource({
    id: "daraz-careers",
    company: "Daraz Bangladesh",
    companyType: "Private",
    sourceName: "Daraz Careers",
    homeUrl: "https://www.daraz.com.bd/",
    careersUrl: "https://www.daraz.com.bd/careers/",
    sectors: ["Ecommerce"],
    notes: "Official Daraz career page verified.",
  }),
  landingSource({
    id: "foodpanda-careers",
    company: "Foodpanda Bangladesh",
    companyType: "Private",
    sourceName: "Foodpanda Careers",
    homeUrl: "https://www.foodpanda.com/",
    careersUrl: "https://www.foodpanda.com/careers/",
    sectors: ["Delivery", "Technology"],
    notes: "Official Foodpanda global careers page verified.",
  }),
  landingSource({
    id: "pran-foods-careers",
    company: "PRAN-RFL",
    companyType: "Private",
    sourceName: "PRAN Foods Career",
    homeUrl: "https://www.pranfoods.net/",
    careersUrl: "https://www.pranfoods.net/career",
    sectors: ["FMCG", "Conglomerate"],
    notes: "Official PRAN Foods career page verified.",
  }),
  landingSource({
    id: "transcom-careers",
    company: "Transcom",
    companyType: "Private",
    sourceName: "Transcom Career",
    homeUrl: "https://www.transcombd.com/",
    careersUrl: "https://www.transcombd.com/career",
    sectors: ["Conglomerate"],
    notes: "Official Transcom career page verified.",
  }),
  landingSource({
    id: "bashundhara-careers",
    company: "Bashundhara Group",
    companyType: "Private",
    sourceName: "Bashundhara Group Careers",
    homeUrl: "https://www.bashundharagroup.com/",
    careersUrl: "https://career.bashundhara.com/",
    sectors: ["Conglomerate"],
    notes: "Updated to the Bashundhara Group career portal URL shared by the user.",
  }),
  landingSource({
    id: "city-group-careers",
    company: "City Group",
    companyType: "Private",
    sourceName: "City Group Career",
    homeUrl: "https://www.citygroup.com.bd/",
    careersUrl: "https://www.citygroup.com.bd/career",
    sectors: ["Conglomerate", "FMCG"],
    notes: "Official City Group career page verified.",
  }),
  landingSource({
    id: "brac-bank-careers",
    company: "BRAC Bank",
    companyType: "Private",
    sourceName: "BRAC Bank Career",
    homeUrl: "https://www.bracbank.com/",
    careersUrl: "https://www.bracbank.com/career",
    sectors: ["Banking"],
    notes: "Updated to the BRAC Bank career URL shared by the user.",
  }),
  landingSource({
    id: "city-bank-careers",
    company: "City Bank",
    companyType: "Private",
    sourceName: "City Bank Career",
    homeUrl: "https://www.thecitybank.com/",
    careersUrl: "https://www.thecitybank.com/career",
    sectors: ["Banking"],
    notes: "Official City Bank career page verified.",
  }),
  landingSource({
    id: "eastern-bank-careers",
    company: "Eastern Bank",
    companyType: "Private",
    sourceName: "Eastern Bank Career",
    homeUrl: "https://www.ebl.com.bd/",
    careersUrl: "https://www.ebl.com.bd/home/career",
    sectors: ["Banking"],
    notes: "Official Eastern Bank career page verified.",
  }),
  landingSource({
    id: "ific-bank-careers",
    company: "IFIC Bank",
    companyType: "Private",
    sourceName: "IFIC Bank Career",
    homeUrl: "https://www.ificbank.com.bd/",
    careersUrl: "https://www.ificbank.com.bd/career",
    sectors: ["Banking"],
    notes: "Official IFIC Bank career page verified.",
  }),
  landingSource({
    id: "mutual-trust-bank-careers",
    company: "Mutual Trust Bank",
    companyType: "Private",
    sourceName: "Mutual Trust Bank Career",
    homeUrl: "https://www.mutualtrustbank.com/",
    careersUrl: "https://www.mutualtrustbank.com/career",
    sectors: ["Banking"],
    notes: "Official Mutual Trust Bank career page verified.",
  }),
  landingSource({
    id: "prime-bank-careers",
    company: "Prime Bank",
    companyType: "Private",
    sourceName: "Prime Bank Career",
    homeUrl: "https://www.primebank.com.bd/",
    careersUrl: "https://www.primebank.com.bd/career",
    sectors: ["Banking"],
    notes: "Official Prime Bank career page verified.",
  }),
  landingSource({
    id: "jamuna-bank-careers",
    company: "Jamuna Bank",
    companyType: "Private",
    sourceName: "Jamuna Bank Career",
    homeUrl: "https://www.jamunabankbd.com/",
    careersUrl: "https://www.jamunabankbd.com/career",
    sectors: ["Banking"],
    notes: "Official Jamuna Bank career page verified.",
  }),
  landingSource({
    id: "midland-bank-careers",
    company: "Midland Bank",
    companyType: "Private",
    sourceName: "Midland Bank Career",
    homeUrl: "https://www.midlandbankbd.net/",
    careersUrl: "https://www.midlandbankbd.net/career",
    sectors: ["Banking"],
    notes: "Official Midland Bank career page verified.",
  }),
  landingSource({
    id: "nrbc-bank-careers",
    company: "NRBC Bank",
    companyType: "Private",
    sourceName: "NRBC Bank Career",
    homeUrl: "https://www.nrbcommercialbank.com/",
    careersUrl: "https://www.nrbcommercialbank.com/career",
    sectors: ["Banking"],
    notes: "Official NRBC Bank career page verified.",
  }),
  landingSource({
    id: "lankabangla-careers",
    company: "LankaBangla Finance",
    companyType: "Private",
    sourceName: "LankaBangla Career",
    homeUrl: "https://www.lankabangla.com/",
    careersUrl: "https://www.lankabangla.com/career",
    sectors: ["Finance"],
    notes: "Official LankaBangla career page verified.",
  }),
  landingSource({
    id: "standard-chartered-careers",
    company: "Standard Chartered",
    companyType: "Multinational",
    sourceName: "Standard Chartered Careers",
    homeUrl: "https://www.standardchartered.com/",
    careersUrl: "https://www.standardchartered.com/careers/",
    sectors: ["Banking"],
    notes: "Official Standard Chartered careers page verified.",
  }),
  landingSource({
    id: "hsbc-careers",
    company: "HSBC",
    companyType: "Multinational",
    sourceName: "HSBC Careers",
    homeUrl: "https://www.hsbc.com/",
    careersUrl: "https://www.hsbc.com/careers/",
    sectors: ["Banking"],
    notes: "Official HSBC careers page verified.",
  }),
  landingSource({
    id: "citi-careers",
    company: "Citi",
    companyType: "Multinational",
    sourceName: "Citi Careers",
    homeUrl: "https://www.citigroup.com/",
    careersUrl: "https://jobs.citi.com/",
    sectors: ["Banking"],
    notes: "Official Citi jobs portal verified.",
  }),
  landingSource({
    id: "samsung-bd-careers",
    company: "Samsung Bangladesh",
    companyType: "Multinational",
    sourceName: "Samsung BD Careers",
    homeUrl: "https://www.samsung.com/bd/",
    careersUrl: "https://www.samsung.com/bd/about-us/careers/",
    sectors: ["Electronics", "Technology"],
    notes: "Official Samsung Bangladesh careers page verified.",
  }),
  landingSource({
    id: "dhl-careers",
    company: "DHL",
    companyType: "Multinational",
    sourceName: "DHL Careers",
    homeUrl: "https://www.dhl.com/",
    careersUrl: "https://careers.dhl.com/global/en",
    sectors: ["Logistics"],
    notes: "Official DHL careers page verified.",
  }),
  landingSource({
    id: "maersk-careers",
    company: "Maersk",
    companyType: "Multinational",
    sourceName: "Maersk Careers",
    homeUrl: "https://www.maersk.com/",
    careersUrl: "https://www.maersk.com/careers/vacancies",
    sectors: ["Logistics"],
    notes: "Official Maersk vacancies page verified.",
  }),
  landingSource({
    id: "unilever-bd-careers",
    company: "Unilever Bangladesh",
    companyType: "Multinational",
    sourceName: "Unilever Bangladesh Careers",
    homeUrl: "https://www.unilever.com/",
    careersUrl: "https://careers.unilever.com/en/bangladesh",
    allowedApplyHosts: ["careers.unilever.com", "unilever.com"],
    sectors: ["FMCG"],
    notes: "Official Unilever Bangladesh careers page verified.",
  }),
  landingSource({
    id: "nestle-bd-careers",
    company: "Nestle Bangladesh",
    companyType: "Multinational",
    sourceName: "Nestle Bangladesh Careers",
    homeUrl: "https://www.nestle.com.bd/",
    careersUrl: "https://www.nestle.com.bd/jobs",
    crawlMode: "browser",
    allowedApplyHosts: [
      "www.nestle.com.bd",
      "nestle.com.bd",
      "career2.successfactors.eu",
    ],
    sectors: ["FMCG"],
    notes:
      "Official Nestle Bangladesh jobs page verified. Browser challenge means parser-safe publishing is disabled for now.",
  }),
  landingSource({
    id: "marico-bd-careers",
    company: "Marico Bangladesh",
    companyType: "Multinational",
    sourceName: "Marico Careers",
    homeUrl: "https://www.marico.com/",
    careersUrl: "https://www.marico.com/bangladesh/careers",
    sectors: ["FMCG"],
    notes: "Official Marico Bangladesh careers page verified.",
  }),
  landingSource({
    id: "berger-careers",
    company: "Berger Bangladesh",
    companyType: "Private",
    sourceName: "Berger Bangladesh Career",
    homeUrl: "https://www.bergerbd.com/",
    careersUrl: "https://www.bergerbd.com/career",
    sectors: ["Paints", "Manufacturing"],
    notes: "Official Berger Bangladesh career page verified.",
  }),
  landingSource({
    id: "reckitt-careers",
    company: "Reckitt",
    companyType: "Multinational",
    sourceName: "Reckitt Careers",
    homeUrl: "https://www.reckitt.com/",
    careersUrl: "https://www.reckitt.com/careers/",
    sectors: ["FMCG"],
    notes: "Official Reckitt careers page verified.",
  }),
  landingSource({
    id: "pepsico-careers",
    company: "PepsiCo",
    companyType: "Multinational",
    sourceName: "PepsiCo Careers",
    homeUrl: "https://www.pepsico.com/",
    careersUrl: "https://careers.pepsico.com/",
    sectors: ["FMCG"],
    notes: "Official PepsiCo careers page verified.",
  }),
  landingSource({
    id: "bat-careers",
    company: "British American Tobacco Bangladesh",
    companyType: "Multinational",
    sourceName: "BAT Careers",
    homeUrl: "https://www.batbangladesh.com/",
    careersUrl: "https://careers.bat.com/",
    sectors: ["FMCG"],
    notes: "Official BAT careers portal verified.",
  }),
  landingSource({
    id: "metlife-bd-careers",
    company: "MetLife Bangladesh",
    companyType: "Multinational",
    sourceName: "MetLife Bangladesh Careers",
    homeUrl: "https://www.metlife.com.bd/",
    careersUrl: "https://www.metlife.com.bd/about-us/careers/",
    sectors: ["Insurance"],
    notes: "Official MetLife Bangladesh careers page verified.",
  }),
  landingSource({
    id: "green-delta-careers",
    company: "Green Delta Insurance",
    companyType: "Private",
    sourceName: "Green Delta Career",
    homeUrl: "https://green-delta.com/",
    careersUrl: "https://green-delta.com/career",
    sectors: ["Insurance"],
    notes: "Official Green Delta career page verified.",
  }),
  landingSource({
    id: "aarong-careers",
    company: "Aarong",
    companyType: "Private",
    sourceName: "Aarong Careers",
    homeUrl: "https://www.aarong.com/",
    careersUrl: "https://www.aarong.com/careers",
    sectors: ["Retail", "Lifestyle"],
    notes: "Official Aarong careers page verified with openings section.",
  }),
  landingSource({
    id: "shwapno-careers",
    company: "Shwapno",
    companyType: "Private",
    sourceName: "Shwapno Career",
    homeUrl: "https://www.shwapno.com/",
    careersUrl: "https://www.shwapno.com/career",
    sectors: ["Super Shop", "Retail"],
    notes: "Official Shwapno career page verified.",
  }),
  landingSource({
    id: "meena-bazar-careers",
    company: "Meena Bazar",
    companyType: "Private",
    sourceName: "Meena Bazar Career",
    homeUrl: "https://www.meenabazar.com.bd/",
    careersUrl: "https://www.meenabazar.com.bd/career",
    sectors: ["Super Shop", "Retail"],
    notes: "Official Meena Bazar career page verified.",
  }),
  landingSource({
    id: "unimart-careers",
    company: "Unimart",
    companyType: "Private",
    sourceName: "Unimart Career",
    homeUrl: "https://unimart.online/",
    careersUrl: "https://unimart.online/career",
    sectors: ["Super Shop", "Retail"],
    notes: "Official Unimart career page verified.",
  }),
  landingSource({
    id: "dbl-group-careers",
    company: "DBL Group",
    companyType: "Private",
    sourceName: "DBL Group Career",
    homeUrl: "https://www.dbl-group.com/",
    careersUrl: "https://www.dbl-group.com/career",
    sectors: ["Manufacturing", "Textiles"],
    notes: "Official DBL Group career page verified.",
  }),
  landingSource({
    id: "fakir-fashion-careers",
    company: "Fakir Fashion",
    companyType: "Private",
    sourceName: "Fakir Fashion Career",
    homeUrl: "https://www.fakirfashion.com/",
    careersUrl: "https://www.fakirfashion.com/career",
    sectors: ["Garments", "Factory"],
    notes: "Official Fakir Fashion career page verified with open positions section.",
  }),
  landingSource({
    id: "babylon-group-careers",
    company: "Babylon Group",
    companyType: "Private",
    sourceName: "Babylon Group Career",
    homeUrl: "https://babylongroup.com/",
    careersUrl: "https://babylongroup.com/career/",
    sectors: ["Garments", "Factory"],
    notes: "Official Babylon Group career page verified.",
  }),
  landingSource({
    id: "edison-group-careers",
    company: "Edison Group",
    companyType: "Private",
    sourceName: "Edison Group Jobs",
    homeUrl: "https://www.edison-bd.com/",
    careersUrl: "https://www.edison-bd.com/career",
    sectors: ["Conglomerate", "Technology"],
    notes: "Official Edison Group jobs page verified.",
  }),
  landingSource({
    id: "abul-khair-group-careers",
    company: "Abul Khair Group",
    companyType: "Private",
    sourceName: "Abul Khair Group Career",
    homeUrl: "https://www.abulkhairgroup.com/",
    careersUrl: "https://www.abulkhairgroup.com/career",
    sectors: ["Factory", "Manufacturing", "Conglomerate"],
    notes: "Official Abul Khair Group career page verified.",
  }),
  landingSource({
    id: "singer-bd-careers",
    company: "Singer Bangladesh",
    companyType: "Private",
    sourceName: "Singer Bangladesh Career",
    homeUrl: "https://www.singerbd.com/",
    careersUrl: "https://www.singerbd.com/career",
    sectors: ["Retail", "Electronics"],
    notes: "Official Singer Bangladesh career page verified.",
  }),
  landingSource({
    id: "rak-ceramics-careers",
    company: "RAK Ceramics Bangladesh",
    companyType: "Private",
    sourceName: "RAK Ceramics Bangladesh Career",
    homeUrl: "https://www.rakceramics.com/bangladesh/en/",
    careersUrl: "https://www.rakceramics.com/bangladesh/en/career",
    sectors: ["Factory", "Manufacturing"],
    notes: "Official RAK Ceramics Bangladesh career page verified.",
  }),
  landingSource({
    id: "aiub-careers",
    company: "American International University-Bangladesh",
    companyType: "Private",
    sourceName: "AIUB Career",
    homeUrl: "https://www.aiub.edu/",
    careersUrl: "https://www.aiub.edu/about/career",
    sectors: ["University", "Education"],
    notes: "Official AIUB career page verified with current vacancies.",
  }),
  landingSource({
    id: "bracu-careers",
    company: "BRAC University",
    companyType: "Private",
    sourceName: "BRAC University Career",
    homeUrl: "https://www.bracu.ac.bd/",
    careersUrl: "https://www.bracu.ac.bd/about/career-at-bracu",
    crawlMode: "browser",
    sectors: ["University", "Education"],
    notes:
      "Official BRAC University career page verified. Browser challenge means parser-safe publishing is disabled for now.",
  }),
  landingSource({
    id: "nsu-erecruitment",
    company: "North South University",
    companyType: "Private",
    sourceName: "NSU E-Recruitment",
    homeUrl: "https://www.northsouth.edu/",
    careersUrl: "https://jobs.northsouth.edu/",
    sectors: ["University", "Education"],
    notes: "Official NSU e-recruitment portal verified.",
  }),
  landingSource({
    id: "nsu-cpc",
    company: "North South University",
    companyType: "Private",
    sourceName: "NSU Career and Placement Center",
    homeUrl: "https://www.northsouth.edu/",
    careersUrl: "https://www.northsouth.edu/cpc",
    sectors: ["University", "Education"],
    notes: "Official NSU Career and Placement Center page verified.",
  }),
  landingSource({
    id: "ewu-careers",
    company: "East West University",
    companyType: "Private",
    sourceName: "East West University Career",
    homeUrl: "https://www.ewubd.edu/",
    careersUrl: "https://www.ewubd.edu/career",
    sectors: ["University", "Education"],
    notes: "Official East West University career page verified.",
  }),
  landingSource({
    id: "uiu-careers",
    company: "United International University",
    companyType: "Private",
    sourceName: "UIU Careers",
    homeUrl: "https://www.uiu.ac.bd/",
    careersUrl: "https://www.uiu.ac.bd/career",
    sectors: ["University", "Education"],
    notes: "Official UIU careers archive verified.",
  }),
  landingSource({
    id: "iubat-careers",
    company: "IUBAT",
    companyType: "Private",
    sourceName: "IUBAT Career",
    homeUrl: "https://iubat.edu/",
    careersUrl: "https://iubat.edu/career/",
    sectors: ["University", "Education"],
    notes: "Official IUBAT career page verified with current vacancies.",
  }),
  landingSource({
    id: "diu-careers",
    company: "Daffodil International University",
    companyType: "Private",
    sourceName: "DIU Career",
    homeUrl: "https://daffodilvarsity.edu.bd/",
    careersUrl: "https://daffodilvarsity.edu.bd/career?app=home&cmd=teaching_roles",
    sectors: ["University", "Education"],
    notes: "Official Daffodil International University career page verified.",
  }),
  landingSource({
    id: "iiuc-careers",
    company: "International Islamic University Chittagong",
    companyType: "Private",
    sourceName: "IIUC Career",
    homeUrl: "https://www.iiuc.ac.bd/",
    careersUrl: "https://cce.iiuc.ac.bd/home/career",
    sectors: ["University", "Education"],
    notes: "Official IIUC career opportunities page verified.",
  }),
  landingSource({
    id: "bubt-careers",
    company: "Bangladesh University of Business and Technology",
    companyType: "Private",
    sourceName: "BUBT Career",
    homeUrl: "https://www.bubt.edu.bd/",
    careersUrl: "https://www.bubt.edu.bd/page/career",
    sectors: ["University", "Education"],
    notes: "Official BUBT career page verified.",
  }),
  landingSource({
    id: "ulab-jobs",
    company: "University of Liberal Arts Bangladesh",
    companyType: "Private",
    sourceName: "ULAB Jobs",
    homeUrl: "https://www.ulab.edu.bd/",
    careersUrl: "https://hr.ulab.edu.bd/jobs-ulab",
    sectors: ["University", "Education"],
    notes: "Official ULAB HR jobs page verified.",
  }),
  landingSource({
    id: "uap-vacancy",
    company: "University of Asia Pacific",
    companyType: "Private",
    sourceName: "UAP Vacancy",
    homeUrl: "https://www.uap-bd.edu/",
    careersUrl: "https://www.uap-bd.edu/vacancy.php",
    sectors: ["University", "Education"],
    notes: "Official UAP vacancy page verified.",
  }),
  landingSource({
    id: "aust-vacancy",
    company: "Ahsanullah University of Science and Technology",
    companyType: "Private",
    sourceName: "AUST Vacancy",
    homeUrl: "https://aust.edu/",
    careersUrl: "https://aust.edu/vacancy",
    sectors: ["University", "Education"],
    notes: "Official AUST vacancy page verified.",
  }),
  landingSource({
    id: "aust-job-opportunities",
    company: "Ahsanullah University of Science and Technology",
    companyType: "Private",
    sourceName: "AUST Job Opportunities",
    homeUrl: "https://www.aust.edu/",
    careersUrl: "https://www.aust.edu/alumni/job_opportunities",
    sectors: ["University", "Education"],
    notes: "Official AUST alumni job opportunities page verified.",
  }),
  landingSource({
    id: "bengal-group-careers",
    company: "Bengal Group",
    companyType: "Private",
    sourceName: "Bengal Group Career",
    homeUrl: "https://www.bengalgroup.com/",
    careersUrl: "https://www.bengalgroup.com/career",
    sectors: ["Manufacturing", "Conglomerate"],
    notes: "Official Bengal Group career page verified.",
  }),
  landingSource({
    id: "square-pharma-careers",
    company: "Square Pharmaceuticals",
    companyType: "Private",
    sourceName: "Square Pharmaceuticals Career",
    homeUrl: "https://squarepharma.com.bd/",
    careersUrl: "https://squarepharma.com.bd/career_4.php",
    sectors: ["Pharma"],
    notes: "Official Square Pharmaceuticals career page verified.",
  }),
  source({
    id: "square-pharma-erecruitment",
    company: "Square Pharmaceuticals",
    companyType: "Private",
    sourceName: "Square Pharmaceuticals eRecruitment",
    homeUrl: "https://squarepharma.com.bd/",
    careersUrl: "https://career.squarepharma.com.bd/",
    listingUrl: "https://career.squarepharma.com.bd/",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["career.squarepharma.com.bd", "squarepharma.com.bd"],
    allowedApplyHosts: ["career.squarepharma.com.bd", "squarepharma.com.bd"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Official Square Pharmaceuticals eRecruitment portal verified and parser-enabled from the user-provided URL.",
  }),
  landingSource({
    id: "incepta-careers",
    company: "Incepta Pharmaceuticals",
    companyType: "Private",
    sourceName: "Incepta Career",
    homeUrl: "https://inceptapharma.com/",
    careersUrl: "https://inceptapharma.com/career/",
    sectors: ["Pharma"],
    notes: "Official Incepta career page verified.",
  }),
  source({
    id: "incepta-current-openings",
    company: "Incepta Pharmaceuticals",
    companyType: "Private",
    sourceName: "Incepta Current Openings",
    homeUrl: "https://inceptapharma.com/",
    careersUrl: "https://inceptapharma.com/career/current-openings.php",
    listingUrl: "https://inceptapharma.com/career/current-openings.php",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["inceptapharma.com", "www.inceptapharma.com"],
    allowedApplyHosts: ["inceptapharma.com", "www.inceptapharma.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Official Incepta current openings page verified and parser-enabled from the user-provided URL family.",
  }),
  landingSource({
    id: "beximco-pharma-careers",
    company: "Beximco Pharmaceuticals",
    companyType: "Private",
    sourceName: "Beximco Pharma Career",
    homeUrl: "https://www.beximco-pharma.com/",
    careersUrl: "https://www.beximco-pharma.com/career/",
    sectors: ["Pharma"],
    notes: "Official Beximco Pharmaceuticals career page verified.",
  }),
  source({
    id: "renata-careers",
    company: "Renata",
    companyType: "Private",
    sourceName: "Renata Career",
    homeUrl: "https://www.renata-ltd.com/",
    careersUrl: "https://career.renata-ltd.com/",
    listingUrl: "https://career.renata-ltd.com/",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["career.renata-ltd.com", "renata-ltd.com", "www.renata-ltd.com"],
    allowedApplyHosts: ["career.renata-ltd.com", "renata-ltd.com", "www.renata-ltd.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Updated to the direct Renata career portal URL shared by the user and parser-enabled.",
  }),
  source({
    id: "eskayef-careers",
    company: "Eskayef Pharmaceuticals",
    companyType: "Private",
    sourceName: "Eskayef Career",
    homeUrl: "https://www.skfbd.com/",
    careersUrl: "https://www.skfbd.com/career",
    listingUrl: "https://www.skfbd.com/career-opportunity",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["www.skfbd.com", "skfbd.com"],
    allowedApplyHosts: ["www.skfbd.com", "skfbd.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes: "Official Eskayef career pages verified and parser-enabled.",
  }),
  landingSource({
    id: "acme-careers",
    company: "ACME Laboratories",
    companyType: "Private",
    sourceName: "ACME Career",
    homeUrl: "https://www.acmeglobal.com/",
    careersUrl: "https://www.acmeglobal.com/career",
    sectors: ["Pharma"],
    notes: "Official ACME Laboratories career page verified.",
  }),
  landingSource({
    id: "opsonin-careers",
    company: "Opsonin Pharma",
    companyType: "Private",
    sourceName: "Opsonin Career",
    homeUrl: "https://www.opsonin-pharma.com/",
    careersUrl: "https://www.opsonin-pharma.com/career",
    listingUrl: "https://www.opsonin-pharma.com/career-opportunity",
    sectors: ["Pharma"],
    notes: "Official Opsonin Pharma career pages verified.",
  }),
  landingSource({
    id: "drug-international-careers",
    company: "Drug International",
    companyType: "Private",
    sourceName: "Drug International Career",
    homeUrl: "https://www.drug-international.com/",
    careersUrl: "https://www.drug-international.com/career",
    listingUrl: "https://www.drug-international.com/career-opportunity",
    sectors: ["Pharma"],
    notes: "Official Drug International career pages verified.",
  }),
  landingSource({
    id: "general-pharma-careers",
    company: "General Pharmaceuticals",
    companyType: "Private",
    sourceName: "General Pharmaceuticals Career",
    homeUrl: "https://www.generalpharma.com/",
    careersUrl: "https://www.generalpharma.com/career",
    sectors: ["Pharma"],
    notes: "Official General Pharmaceuticals career page verified.",
  }),
  landingSource({
    id: "popular-pharma-careers",
    company: "Popular Pharmaceuticals",
    companyType: "Private",
    sourceName: "Popular Pharmaceuticals Career",
    homeUrl: "https://www.popular-pharma.com/",
    careersUrl: "https://www.popular-pharma.com/career",
    sectors: ["Pharma"],
    notes:
      "Official Popular Pharmaceuticals career page verified through official site search results.",
  }),
  source({
    id: "beacon-pharma-careers",
    company: "Beacon Pharmaceuticals",
    companyType: "Private",
    sourceName: "Beacon Pharmaceuticals Career",
    homeUrl: "https://www.beaconpharma.com.bd/",
    careersUrl: "https://beaconpharma.com.bd/careers",
    listingUrl: "https://beaconpharma.com.bd/careers",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["beaconpharma.com.bd", "www.beaconpharma.com.bd"],
    allowedApplyHosts: ["beaconpharma.com.bd", "www.beaconpharma.com.bd"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Updated to the Beacon careers URL shared by the user and parser-enabled.",
  }),
  landingSource({
    id: "radiant-pharma-careers",
    company: "Radiant Pharmaceuticals",
    companyType: "Private",
    sourceName: "Radiant Pharmaceuticals Career",
    homeUrl: "https://www.radiantpharmabd.com/",
    careersUrl: "https://www.radiantpharmabd.com/career",
    sectors: ["Pharma"],
    notes: "Official Radiant Pharmaceuticals career page verified.",
  }),
  landingSource({
    id: "biopharma-careers",
    company: "Biopharma",
    companyType: "Private",
    sourceName: "Biopharma Career",
    homeUrl: "https://www.biopharmabd.com/",
    careersUrl: "https://www.biopharmabd.com/job-carrer",
    listingUrl: "https://www.biopharmabd.com/job-apply/6",
    sectors: ["Pharma"],
    notes:
      "Official Biopharma career endpoints verified through official site search results.",
  }),
  source({
    id: "healthcare-pharma-jobs",
    company: "Healthcare Pharmaceuticals",
    companyType: "Private",
    sourceName: "Healthcare Pharmaceuticals Jobs",
    homeUrl: "https://www.hplbd.com/",
    careersUrl: "https://hris.hplbd.com/jobs",
    listingUrl: "https://hris.hplbd.com/jobs",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["hris.hplbd.com", "hplbd.com", "www.hplbd.com"],
    allowedApplyHosts: ["hris.hplbd.com", "hplbd.com", "www.hplbd.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided Healthcare Pharmaceuticals jobs portal URL.",
  }),
  source({
    id: "navana-pharma-circulars",
    company: "Navana Pharmaceuticals",
    companyType: "Private",
    sourceName: "Navana Pharma Circulars",
    homeUrl: "https://www.navanapharma.com/",
    careersUrl: "https://www.navanapharma.com/career/circulars",
    listingUrl: "https://www.navanapharma.com/career/circulars",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["www.navanapharma.com", "navanapharma.com"],
    allowedApplyHosts: ["www.navanapharma.com", "navanapharma.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided Navana Pharmaceuticals circulars URL.",
  }),
  landingSource({
    id: "nuvista-pharma-careers",
    company: "Nuvista Pharma",
    companyType: "Private",
    sourceName: "Nuvista Pharma Career",
    homeUrl: "https://nuvistapharma.com/",
    careersUrl: "https://nuvistapharma.com/career",
    sectors: ["Pharma"],
    notes: "Added from the user-provided Nuvista Pharma career URL.",
  }),
  source({
    id: "aci-careers",
    company: "ACI",
    companyType: "Private",
    sourceName: "ACI Career",
    homeUrl: "https://www.aci-bd.com/",
    careersUrl: "https://www.aci-bd.com/career",
    listingUrl: "https://www.aci-bd.com/career",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["www.aci-bd.com", "aci-bd.com"],
    allowedApplyHosts: ["www.aci-bd.com", "aci-bd.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Pharma", "Conglomerate"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided ACI career URL.",
  }),
  source({
    id: "walton-jobs",
    company: "Walton",
    companyType: "Private",
    sourceName: "Walton Jobs",
    homeUrl: "https://www.waltonbd.com/",
    careersUrl: "https://jobs.waltonbd.com/",
    listingUrl: "https://jobs.waltonbd.com/",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["jobs.waltonbd.com", "waltonbd.com", "www.waltonbd.com"],
    allowedApplyHosts: ["jobs.waltonbd.com", "waltonbd.com", "www.waltonbd.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Electronics", "Manufacturing"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided Walton jobs portal URL.",
  }),
  source({
    id: "ananta-careers",
    company: "Ananta Group",
    companyType: "Private",
    sourceName: "Ananta Career",
    homeUrl: "https://www.ananta.com.bd/",
    careersUrl: "https://www.ananta.com.bd/career.php",
    listingUrl: "https://www.ananta.com.bd/career.php",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["www.ananta.com.bd", "ananta.com.bd"],
    allowedApplyHosts: ["www.ananta.com.bd", "ananta.com.bd"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Garments", "Manufacturing"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided Ananta career URL.",
  }),
  source({
    id: "urmi-group-careers",
    company: "Urmi Group",
    companyType: "Private",
    sourceName: "Urmi Group Career",
    homeUrl: "https://urmigroup.com/",
    careersUrl: "https://urmigroup.com/career",
    listingUrl: "https://urmigroup.com/career",
    adapter: "genericOfficialCareer",
    crawlMode: "html",
    allowHosts: ["urmigroup.com", "www.urmigroup.com"],
    allowedApplyHosts: ["urmigroup.com", "www.urmigroup.com"],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Garments", "Manufacturing"],
    lastVerifiedAt: "2026-05-01",
    notes: "Added from the user-provided Urmi Group career URL.",
  }),
  landingSource({
    id: "robi-careers",
    company: "Robi",
    companyType: "Private",
    sourceName: "Robi Career",
    homeUrl: "https://www.robi.com.bd/",
    careersUrl: "https://robicareer.com/",
    sectors: ["Telecom"],
    notes: "Added from the user-provided Robi career portal URL.",
  }),
  landingSource({
    id: "bdjobs-company-9770",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 9770",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=9770",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-23085",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 23085",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=23085",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-15631",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 15631",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=15631",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-20383",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 20383",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=20383",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-43950",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 43950",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=43950",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-16714",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 16714",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=16714",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-banglalink-company-page",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Banglalink Company Page",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://banglalink.bdjobs.com/",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Banglalink Bdjobs URL.",
  }),
  landingSource({
    id: "bdjobs-company-28714",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 28714",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=28714",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-33621",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 33621",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=33621",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-company-25910",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Company Page 25910",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/companyofferedjobs.asp?id=25910",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs company page URL.",
  }),
  landingSource({
    id: "bdjobs-category-11",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 11",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=11",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-6",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 6",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=6",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-2",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 2",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=2",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-8",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 8",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=8",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-12",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 12",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=12",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-20",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 20",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=20",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-1",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 1",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=1",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-3",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 3",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=3",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-4",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 4",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=4",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-5",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 5",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=5",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-7",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 7",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=7",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-9",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 9",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=9",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-10",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 10",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=10",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-13",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 13",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=13",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-category-14",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs Category 14",
    sourceChannel: "verified-board",
    homeUrl: "https://jobs.bdjobs.com/",
    careersUrl: "https://jobs.bdjobs.com/jobsearch.asp?fcatId=14",
    sectors: ["Trusted Job Board"],
    notes: "Added from the user-provided Bdjobs category URL.",
  }),
  landingSource({
    id: "bdjobs-verified-board",
    company: "Bdjobs",
    companyType: "Trusted Platform",
    sourceName: "Bdjobs",
    sourceChannel: "verified-board",
    homeUrl: "https://bdjobs.com/",
    careersUrl: "https://bdjobs.com/",
    sectors: ["Trusted Job Board"],
    notes:
      "Trusted public Bangladesh job platform verified. Use only direct listing/source links and keep publishing conservative.",
  }),
  source({
    id: "biman-jobs-board",
    company: "Biman Bangladesh Airlines",
    companyType: "Government",
    sourceName: "Biman Job Corner",
    sourceChannel: "verified-board",
    homeUrl: "https://biman.gov.bd/",
    careersUrl: "https://biman.gov.bd/site/view/jobs",
    listingUrl: "https://biman.gov.bd/site/view/jobs",
    adapter: "govtPortalTable",
    crawlMode: "html",
    allowHosts: ["biman.gov.bd"],
    allowedApplyHosts: [
      "biman.gov.bd",
      "objectstorage.ap-dcc-gazipur-1.oraclecloud15.com",
    ],
    enabled: true,
    official: true,
    trusted: true,
    sectors: ["Government", "Transport"],
    lastVerifiedAt: "2026-05-01",
    notes:
      "Official Biman Bangladesh Airlines jobs table verified and parser-enabled.",
  }),
  landingSource({
    id: "bangladesh-police-jobs-board",
    company: "Bangladesh Police",
    companyType: "Government",
    sourceName: "Bangladesh Police Recruitment",
    sourceChannel: "verified-board",
    homeUrl: "https://police.portal.gov.bd/",
    careersUrl:
      "https://police.portal.gov.bd/site/page/52cad7e8-468a-4d54-802d-9e62437307b4/-",
    sectors: ["Government", "Security"],
    notes:
      "Official Bangladesh Police recruitment page verified.",
  }),
  landingSource({
    id: "bangladesh-army-join-board",
    company: "Bangladesh Army",
    companyType: "Government",
    sourceName: "Join Bangladesh Army",
    sourceChannel: "verified-board",
    homeUrl: "https://joinbangladesharmy.army.mil.bd/",
    careersUrl: "https://joinbangladesharmy.army.mil.bd/",
    allowedApplyHosts: [
      "joinbangladesharmy.army.mil.bd",
      "join.army.mil.bd",
      "sainik.teletalk.com.bd",
    ],
    sectors: ["Government", "Defense"],
    notes:
      "Official Bangladesh Army recruitment portal verified. Includes commissioned officer and soldier pathways.",
  }),
  landingSource({
    id: "bangladesh-navy-join-board",
    company: "Bangladesh Navy",
    companyType: "Government",
    sourceName: "Join Bangladesh Navy",
    sourceChannel: "verified-board",
    homeUrl: "https://www.joinnavy.navy.mil.bd/",
    careersUrl: "https://www.joinnavy.navy.mil.bd/",
    allowedApplyHosts: [
      "www.joinnavy.navy.mil.bd",
      "joinnavy.navy.mil.bd",
      "joinnavyofficer.org",
      "joinnavysailor.org",
      "navy.mil.bd",
    ],
    sectors: ["Government", "Defense"],
    notes:
      "Official Bangladesh Navy recruitment portal verified. Includes officer and sailor entry information.",
  }),
  landingSource({
    id: "bangladesh-navy-recruitment-page",
    company: "Bangladesh Navy",
    companyType: "Government",
    sourceName: "Bangladesh Navy Recruitment",
    sourceChannel: "verified-board",
    homeUrl: "https://navy.mil.bd/",
    careersUrl: "https://navy.mil.bd/page/recruitment",
    allowedApplyHosts: [
      "navy.mil.bd",
      "joinnavyofficer.org",
      "joinnavysailor.org",
      "www.joinnavy.navy.mil.bd",
    ],
    sectors: ["Government", "Defense"],
    notes:
      "Official Bangladesh Navy recruitment information page verified.",
  }),
];

export const pendingTrustedSourceResearch = [
  "Akij Group official career page still needs a stable verified jobs URL",
  "Aristopharma official career page still needs a stable verified jobs URL",
  "Meghna Group official career page still needs a stable verified jobs URL",
  "Coca-Cola Bangladesh location-specific careers URL still needs verification",
] as const;

// Add new trusted sources here only after verifying:
// 1. The URL is official and owned by the company or its official career system.
// 2. The page is not a 404, parked domain, or fake redirect.
// 3. The page can be crawled safely without violating robots.txt or source terms.
// 4. If parser confidence is not yet good enough, keep enabled=false and use landingOnly.

export function getSourceById(sourceId: string) {
  return trustedSourceRegistry.find((entry) => entry.id === sourceId) ?? null;
}

export function getSourceByCompanySlug(companySlug: string) {
  return trustedSourceRegistry.find((entry) => entry.companySlug === companySlug) ?? null;
}
